name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  SOLANA_CLI_VERSION: 1.8.5
  NODE_VERSION: 17.0.1

jobs:
  setup-anchor-cli:
    name: Setup Anchor cli
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup/

      - uses: actions/cache@v2
        name: Cache Cargo registry + index
        id: cache-anchor
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
          key: cargo-${{ runner.os }}-anchor-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo install --path cli anchor-cli --locked --force
      - uses: actions/upload-artifact@v2
        with:
          name: anchor-binary
          path: ~/.cargo/bin/anchor

  test-programs:
    needs: setup-anchor-cli
    name: Test Programs
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-ts/
      - uses: ./.github/actions/setup-solana/
      - uses: ./.github/actions/setup-anchor/

      - uses: actions/cache@v2
        name: Cache Cargo registry + index
        id: cache-anchor
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
          key: cargo-${{ runner.os }}-anchor-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/download-artifact@v2
        with:
          name: anchor-binary
          path: ~/.cargo/bin/

      - uses: actions/cache@v2
        name: Cache target
        id: cache-test-target
        with:
          path: target
          key: cargo-${{ runner.os }}-target-${{ env.ANCHOR_VERSION }}

      - run: anchor test
        name: program test
